name: boss
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  fluttertoast: 2.0.9
  event_bus: ^1.0.1
  flutter_html_view: ^0.5.10
  scoped_model: ^0.3.0
  http: ^0.12.0
  flutter_redux: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/ic_main_tab_company_nor.png
  - assets/images/ic_main_tab_company_pre.png
  - assets/images/ic_main_tab_contacts_nor.png
  - assets/images/ic_main_tab_contacts_pre.png
  - assets/images/ic_main_tab_find_nor.png
  - assets/images/ic_main_tab_find_pre.png
  - assets/images/ic_main_tab_my_nor.png
  - assets/images/ic_main_tab_my_pre.png
  -
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/font/dosis/Dosis-Bold-5.ttf
        - asset: assets/font/dosis/Dosis-ExtraBold-7.ttf
        - asset: assets/font/dosis/Dosis-ExtraLight-8.ttf
        - asset: assets/font/dosis/Dosis-Light-4.ttf
        - asset: assets/font/dosis/Dosis-Medium-3.ttf
        - asset: assets/font/dosis/Dosis-Regular-2.ttf
        - asset: assets/font/dosis/Dosis-SemiBold-6.ttf